add_library(perfetto STATIC)

target_include_directories(perfetto
PRIVATE
    third_party/abseil-cpp
)

target_compile_options(perfetto PRIVATE "/FC")

include(cmake/nice_target_sources.cmake)

target_compile_options(perfetto PRIVATE
    -Wno-missing-template-arg-list-after-template-kw
)

target_include_directories(perfetto
PRIVATE    
    third_party/perfetto
    third_party/perfetto/include
    gen/third_party/perfetto/
    gen/third_party/perfetto/build_config
)

  nice_target_sources(perfetto "gen/third_party/perfetto/protos/perfetto"
    PRIVATE
trace/track_event/chrome_application_state_info.gen.cc
trace/track_event/chrome_application_state_info.gen.h
trace/track_event/chrome_application_state_info.pb.h
trace/track_event/chrome_application_state_info.pbzero.cc
trace/track_event/chrome_application_state_info.pbzero.h
trace/track_event/chrome_compositor_scheduler_state.gen.cc
trace/track_event/chrome_compositor_scheduler_state.gen.h
trace/track_event/chrome_compositor_scheduler_state.pb.h
trace/track_event/chrome_compositor_scheduler_state.pbzero.cc
trace/track_event/chrome_compositor_scheduler_state.pbzero.h
trace/track_event/chrome_content_settings_event_info.gen.cc
trace/track_event/chrome_content_settings_event_info.gen.h
trace/track_event/chrome_content_settings_event_info.pb.h
trace/track_event/chrome_content_settings_event_info.pbzero.cc
trace/track_event/chrome_content_settings_event_info.pbzero.h
trace/track_event/chrome_frame_reporter.gen.cc
trace/track_event/chrome_frame_reporter.gen.h
trace/track_event/chrome_frame_reporter.pb.h
trace/track_event/chrome_frame_reporter.pbzero.cc
trace/track_event/chrome_frame_reporter.pbzero.h
trace/track_event/chrome_histogram_sample.gen.cc
trace/track_event/chrome_histogram_sample.gen.h
trace/track_event/chrome_histogram_sample.pb.h
trace/track_event/chrome_histogram_sample.pbzero.cc
trace/track_event/chrome_histogram_sample.pbzero.h
trace/track_event/chrome_keyed_service.gen.cc
trace/track_event/chrome_keyed_service.gen.h
trace/track_event/chrome_keyed_service.pb.h
trace/track_event/chrome_keyed_service.pbzero.cc
trace/track_event/chrome_keyed_service.pbzero.h
trace/track_event/chrome_latency_info.gen.cc
trace/track_event/chrome_latency_info.gen.h
trace/track_event/chrome_latency_info.pb.h
trace/track_event/chrome_latency_info.pbzero.cc
trace/track_event/chrome_latency_info.pbzero.h
trace/track_event/chrome_legacy_ipc.gen.cc
trace/track_event/chrome_legacy_ipc.gen.h
trace/track_event/chrome_legacy_ipc.pb.h
trace/track_event/chrome_legacy_ipc.pbzero.cc
trace/track_event/chrome_legacy_ipc.pbzero.h
trace/track_event/chrome_message_pump.gen.cc
trace/track_event/chrome_message_pump.gen.h
trace/track_event/chrome_message_pump.pb.h
trace/track_event/chrome_message_pump.pbzero.cc
trace/track_event/chrome_message_pump.pbzero.h
trace/track_event/chrome_mojo_event_info.gen.cc
trace/track_event/chrome_mojo_event_info.gen.h
trace/track_event/chrome_mojo_event_info.pb.h
trace/track_event/chrome_mojo_event_info.pbzero.cc
trace/track_event/chrome_mojo_event_info.pbzero.h
trace/track_event/chrome_process_descriptor.gen.cc
trace/track_event/chrome_process_descriptor.gen.h
trace/track_event/chrome_process_descriptor.pb.h
trace/track_event/chrome_process_descriptor.pbzero.cc
trace/track_event/chrome_process_descriptor.pbzero.h
trace/track_event/chrome_renderer_scheduler_state.gen.cc
trace/track_event/chrome_renderer_scheduler_state.gen.h
trace/track_event/chrome_renderer_scheduler_state.pb.h
trace/track_event/chrome_renderer_scheduler_state.pbzero.cc
trace/track_event/chrome_renderer_scheduler_state.pbzero.h
trace/track_event/chrome_thread_descriptor.gen.cc
trace/track_event/chrome_thread_descriptor.gen.h
trace/track_event/chrome_thread_descriptor.pb.h
trace/track_event/chrome_thread_descriptor.pbzero.cc
trace/track_event/chrome_thread_descriptor.pbzero.h
trace/track_event/chrome_user_event.gen.cc
trace/track_event/chrome_user_event.gen.h
trace/track_event/chrome_user_event.pb.h
trace/track_event/chrome_user_event.pbzero.cc
trace/track_event/chrome_user_event.pbzero.h
trace/track_event/chrome_window_handle_event_info.gen.cc
trace/track_event/chrome_window_handle_event_info.gen.h
trace/track_event/chrome_window_handle_event_info.pb.h
trace/track_event/chrome_window_handle_event_info.pbzero.cc
trace/track_event/chrome_window_handle_event_info.pbzero.h
trace/track_event/counter_descriptor.gen.cc
trace/track_event/counter_descriptor.gen.h
trace/track_event/counter_descriptor.pb.h
trace/track_event/counter_descriptor.pbzero.cc
trace/track_event/counter_descriptor.pbzero.h
trace/track_event/debug_annotation.gen.cc
trace/track_event/debug_annotation.gen.h
trace/track_event/debug_annotation.pb.h
trace/track_event/debug_annotation.pbzero.cc
trace/track_event/debug_annotation.pbzero.h
trace/track_event/log_message.gen.cc
trace/track_event/log_message.gen.h
trace/track_event/log_message.pb.h
trace/track_event/log_message.pbzero.cc
trace/track_event/log_message.pbzero.h
trace/track_event/process_descriptor.gen.cc
trace/track_event/process_descriptor.gen.h
trace/track_event/process_descriptor.pb.h
trace/track_event/process_descriptor.pbzero.cc
trace/track_event/process_descriptor.pbzero.h
trace/track_event/source_location.gen.cc
trace/track_event/source_location.gen.h
trace/track_event/source_location.pb.h
trace/track_event/source_location.pbzero.cc
trace/track_event/source_location.pbzero.h
trace/track_event/source_set
trace/track_event/task_execution.gen.cc
trace/track_event/task_execution.gen.h
trace/track_event/task_execution.pb.h
trace/track_event/task_execution.pbzero.cc
trace/track_event/task_execution.pbzero.h
trace/track_event/thread_descriptor.gen.cc
trace/track_event/thread_descriptor.gen.h
trace/track_event/thread_descriptor.pb.h
trace/track_event/thread_descriptor.pbzero.cc
trace/track_event/thread_descriptor.pbzero.h
trace/track_event/track_descriptor.gen.cc
trace/track_event/track_descriptor.gen.h
trace/track_event/track_descriptor.pb.h
trace/track_event/track_descriptor.pbzero.cc
trace/track_event/track_descriptor.pbzero.h
trace/track_event/track_event.descriptor
trace/track_event/track_event.descriptor.d
trace/track_event/track_event.gen.cc
trace/track_event/track_event.gen.h
trace/track_event/track_event.pb.h
trace/track_event/track_event.pbzero.cc
trace/track_event/track_event.pbzero.h
trace/interned_data/interned_data.pbzero.cc
trace/interned_data/interned_data.pbzero.h
trace/memory_graph.pbzero.cc
trace/memory_graph.pbzero.h
trace/trace_packet.pbzero.cc
trace/trace_packet.pbzero.h
common/builtin_clock.pbzero.cc
common/builtin_clock.pbzero.h
common/data_source_descriptor.gen.cc
  )

  nice_target_sources(perfetto "third_party/perfetto"
    PRIVATE
src/base/http/http_server.cc
src/base/http/sha1.cc
src/base/android_utils.cc
src/base/base64.cc
src/base/crash_keys.cc
src/base/ctrl_c_handler.cc
src/base/event_fd.cc
src/base/file_utils.cc
src/base/getopt_compat.cc
src/base/logging.cc
src/base/metatrace.cc
src/base/paged_memory.cc
src/base/periodic_task.cc
src/base/pipe.cc
src/base/status.cc
src/base/string_splitter.cc
src/base/string_utils.cc
src/base/string_view.cc
src/base/subprocess.cc
src/base/subprocess_posix.cc
src/base/subprocess_windows.cc
src/base/temp_file.cc
src/base/thread_checker.cc
src/base/thread_task_runner.cc
src/base/time.cc
src/base/unix_task_runner.cc
src/base/utils.cc
src/base/uuid.cc
src/base/version.cc
src/base/virtual_destructors.cc
src/base/waitable_event.cc
src/base/watchdog_posix.cc
src/base/unix_socket.cc
src/protozero/field.cc
src/protozero/message.cc
src/protozero/message_arena.cc
src/protozero/message_handle.cc
src/protozero/packed_repeated_fields.cc
src/protozero/proto_decoder.cc
src/protozero/scattered_heap_buffer.cc
src/protozero/scattered_stream_null_delegate.cc
src/protozero/scattered_stream_writer.cc
src/protozero/static_buffer.cc
src/protozero/virtual_destructors.cc
src/tracing/traced_value.cc
src/tracing/internal/checked_scope.cc
src/tracing/internal/track_event_interned_fields.cc
src/tracing/internal/track_event_internal.cc
src/tracing/track_event_category_registry.cc
src/tracing/event_context.cc
src/tracing/track.cc
src/tracing/platform.cc
src/tracing/virtual_destructors.cc
)
